background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 6
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    rounding = 8
    position = 0, -40
    halign = center
    valign = center
}
